#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# dev-up.sh — Start an isolated et-shop dev stack
#
# Usage:
#   bash scripts/dev-up.sh
#   bash scripts/dev-up.sh --port-web 3000 --port-studio 54323
#
# Requirements: Docker >= 24, Docker Compose v2, curl
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DOCKER_DIR="${REPO_ROOT}/docker"
FEAT="dev_env_docker"

# ── Defaults ──────────────────────────────────────────────────────────────────
PORT_WEB=""
PORT_STUDIO=""

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --port-web)    PORT_WEB="$2";    shift 2 ;;
    --port-studio) PORT_STUDIO="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ── Helper: find a free port starting from $1 ─────────────────────────────────
find_free_port() {
  local start="$1"
  local port="$start"
  while true; do
    if ! lsof -i :"${port}" -sTCP:LISTEN -t >/dev/null 2>&1 && \
       ! ss -tlnp 2>/dev/null | grep -q ":${port} "; then
      echo "$port"
      return 0
    fi
    port=$((port + 1))
  done
}

# ── Auto-detect ports if not provided ────────────────────────────────────────
if [[ -z "$PORT_WEB" ]]; then
  PORT_WEB="$(find_free_port 3000)"
fi
if [[ -z "$PORT_STUDIO" ]]; then
  PORT_STUDIO="$(find_free_port 54323)"
fi

# Derived ports (fixed offsets from PORT_WEB base, or auto-detect)
PORT_API="$(find_free_port $((PORT_WEB + 1)))"
PORT_DB="$(find_free_port 54322)"
PORT_KONG="$(find_free_port 54321)"
PORT_INBUCKET="$(find_free_port 54324)"

PROJECT_NAME="etshop_${PORT_WEB}"
ENV_FILE="${DOCKER_DIR}/.env.${PORT_WEB}"

# ── Generate instance .env ────────────────────────────────────────────────────
cat > "${ENV_FILE}" <<EOF
# Generated by dev-up.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
PROJECT_NAME=${PROJECT_NAME}
FEAT=${FEAT}
PORT_WEB=${PORT_WEB}
PORT_API=${PORT_API}
PORT_STUDIO=${PORT_STUDIO}
PORT_DB=${PORT_DB}
PORT_KONG=${PORT_KONG}
PORT_INBUCKET=${PORT_INBUCKET}
POSTGRES_PASSWORD=postgres
JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters
ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYxMzUzMTk4NSwiZXhwIjo0NzY5MjA1OTg1fQ.nnJMI5BnvLXqVLdpQMvVHNLuFwBp_Ib6BRn0IG8c0lY
SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjEzNTMxOTg1LCJleHAiOjQ3NjkyMDU5ODV9.blh3BFdSIYLg24OMpRi3ZlmP_-N2sAIkpILNKnpzMjk
EOF

echo "Starting instance: ${PROJECT_NAME}"
echo "  PORT_WEB      = ${PORT_WEB}"
echo "  PORT_API      = ${PORT_API}"
echo "  PORT_STUDIO   = ${PORT_STUDIO}"
echo "  PORT_DB       = ${PORT_DB}"
echo "  PORT_KONG     = ${PORT_KONG}"
echo "  PORT_INBUCKET = ${PORT_INBUCKET}"
echo "  ENV_FILE      = ${ENV_FILE}"
echo ""

docker compose \
  -p "${PROJECT_NAME}" \
  -f "${DOCKER_DIR}/compose.yml" \
  --env-file "${ENV_FILE}" \
  up -d

echo ""
echo "Stack is up!"
echo "  Web:    http://localhost:${PORT_WEB}"
echo "  API:    http://localhost:${PORT_API}"
echo "  Studio: http://localhost:${PORT_STUDIO}"
echo "  Kong:   http://localhost:${PORT_KONG}"
